name: RustDesk Remote (Windows Server 2022)
on: workflow_dispatch

jobs:
  remote:
    runs-on: windows-latest    # Windows Server 2022 runner
    timeout-minutes: 360

    steps:
      - name: Prep PowerShell
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          Write-Host "OS:" (Get-ComputerInfo).OsName (Get-ComputerInfo).OsVersion

      - name: Install Chocolatey
        shell: pwsh
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force
          [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
          Invoke-Expression ((New-Object Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
          choco --version

      - name: Install RustDesk (portable)
        shell: pwsh
        run: |
          choco install rustdesk.portable -y --no-progress
          # Get the shimmed path to rustdesk.exe
          $global:RustDeskExe = (Get-Command rustdesk.exe -ErrorAction Stop).Source
          Write-Host "RustDesk exe: $global:RustDeskExe"

      - name: Set unattended password and start RustDesk
        shell: pwsh
        run: |
          $rd = (Get-Command rustdesk.exe).Source
          # Set permanent password (no env vars)
          & $rd --password "vnc@4321"
          # Start RustDesk UI (helps with permissions/UAC)
          Start-Process -FilePath $rd -WindowStyle Hidden
          Start-Sleep -Seconds 5

      - name: Show RustDesk ID (use this to connect)
        shell: pwsh
        run: |
          $rd = (Get-Command rustdesk.exe).Source
          $id = ""
          for ($i=0; $i -lt 30 -and [string]::IsNullOrWhiteSpace($id); $i++) {
            try {
              $id = (& $rd --get-id) 2>$null
              if (-not [string]::IsNullOrWhiteSpace($id)) { break }
            } catch { }
            Start-Sleep -Seconds 2
          }
          Write-Host "----------------------------------------------------"
          if ([string]::IsNullOrWhiteSpace($id)) {
            Write-Host "RustDesk ID not yet available. Wait a bit and rerun the step/logs."
          } else {
            Write-Host "RustDesk ID: $id"
          }
          Write-Host "Password   : vnc@4321"
          Write-Host "Open RustDesk on your computer, enter the ID above, and connect."
          Write-Host "----------------------------------------------------"

      - name: Keep alive
        shell: pwsh
        run: |
          for ($i=0; $i -lt 43200; $i++) {
            Write-Host "alive $(Get-Date -Format s)"
            Start-Sleep -Seconds 60
          }
