name: RustDesk Remote (Windows Server 2022)
on: workflow_dispatch

jobs:
  remote:
    runs-on: windows-latest   # Windows Server 2022 runner
    timeout-minutes: 360

    steps:
      - name: Prep PowerShell
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          Write-Host "OS:" (Get-ComputerInfo).OsName (Get-ComputerInfo).OsVersion

      - name: Download RustDesk (portable)
        shell: pwsh
        run: |
          # Grab latest stable portable build (x64)
          $url = "https://github.com/rustdesk/rustdesk/releases/latest/download/rustdesk-1.2.3-x86_64-pc-windows-msvc-portable.zip"
          $zip = "$env:USERPROFILE\rustdesk.zip"
          $dir = "$env:USERPROFILE\rustdesk"
          Invoke-WebRequest -Uri $url -OutFile $zip
          if (Test-Path $dir) { Remove-Item $dir -Recurse -Force }
          Expand-Archive -Path $zip -DestinationPath $dir
          Get-ChildItem $dir

      - name: Set unattended password and start RustDesk
        shell: pwsh
        run: |
          $rd = Get-ChildItem "$env:USERPROFILE\rustdesk\*.exe" | Where-Object { $_.Name -match 'rustdesk.*\.exe$' } | Select-Object -First 1
          if (-not $rd) { throw "RustDesk executable not found." }

          # Set permanent password (unattended access)
          # Official docs: --password sets a permanent password; --get-id prints the ID. :contentReference[oaicite:0]{index=0}
          & $rd.FullName --password "vnc@4321"

          # Launch RustDesk elevated if possible (helps with UAC prompts)
          # Portable elevation tips are documented by RustDesk. :contentReference[oaicite:1]{index=1}
          Start-Process -FilePath $rd.FullName -Verb RunAs

          Start-Sleep -Seconds 5

      - name: Show RustDesk ID (use this to connect)
        shell: pwsh
        run: |
          $rd = Get-ChildItem "$env:USERPROFILE\rustdesk\*.exe" | Where-Object { $_.Name -match 'rustdesk.*\.exe$' } | Select-Object -First 1
          $id = & $rd.FullName --get-id
          Write-Host "----------------------------------------------------"
          Write-Host "RustDesk ID: $id"
          Write-Host "Password   : vnc@4321"
          Write-Host "Open RustDesk on your computer, enter the ID above, and connect."
          Write-Host "----------------------------------------------------"

      - name: Keep alive
        shell: pwsh
        run: |
          for ($i=0; $i -lt 43200; $i++) {
            Write-Host "alive $(Get-Date -Format s)"
            Start-Sleep -Seconds 60
          }
